<?php
// $Id;

/**
 * @file
 *  IDS Views install file.
 */

/**
 * Implements hook_enable()
 */
function idsviews_enable() {
  drupal_flush_all_caches();
}

/**
 * Implements hook_disable()
 */
function idsviews_disable() {
  $default_views_names = array('ids_documents_view','ids_organisations_view');
  foreach ($default_views_names as $view_name) {
    if ($view = views_get_view($view_name)) {
      $view->disabled = TRUE;
    }
  }
  drupal_flush_all_caches();
}





